version: '3.5'

services:
  medine-php81-symfony54:
    container_name: medine-php81-symfony54
    build:
      context: ./docker
      args:
        UID: $U_ID
    volumes:
      - ./:/appdata/www
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=medine-php81-symfony54
    ports:
      - '1000:8000'
    networks:
      - medine-php81-symfony54-network
networks:
  medine-php81-symfony54-network:
